package com.bjpowernode.crm.setting.mapper;

import com.bjpowernode.crm.setting.domain.User;

import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Jul 03 20:45:10 CST 2024
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Jul 03 20:45:10 CST 2024
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Jul 03 20:45:10 CST 2024
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Jul 03 20:45:10 CST 2024
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Jul 03 20:45:10 CST 2024
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed Jul 03 20:45:10 CST 2024
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据账号和密码查询用户
     *
     * @param:  [map]
     * @return: com.bjpowernode.crm.setting.domain.User
     * @date:   2024/7/3 22:29
     **/
    User selectUserByLoginActAndPwd(Map<String,Object> map);


}